### PR TITLE
fix: use fixed versions

### PR DESCRIPTION
**Pull request by kuisathaverat**
reviewing the packages used in this project we detected that we are not using fixed versions, ~and there was some security issues~. This PR adds the `package-lock.json` file to resolve the issue.

### CODE REVIEW

**Review by mdelapenya — APPROVED** [review]

**Comment by trentm** [comment]
When I run `npm audit` at the top-level on a clean build of opbeans-node, I get no vulnerabilities:

```
[8:36:13 trentm@pink:~/el/opbeans-node (n:14 git:master)]
% npm audit

                       === npm audit security report ===

found 0 vulnerabilities
 in 434 scanned packages
```

Did you have a working copy that was showing vulnerabilities because of an older uncommitted package-lock.json file?

Adding a package-lock.json file will tend to mean that we *don't* automatically get security updates from dependencies as they are published, but will require manually updating package-lock.json occasionally. However having a package-lock.json file *will* mean we  (a) will have more reproducible builds and (b) can manually update transitive deps if/when security updates are provided (e.g. upgrading "workload"'s version of "minimist" if minimist has a security fix, but workload hasn't yet been updated.

**Comment by trentm** [comment]
Note as well that from this commit:

```
commit eb95afc816953dcefb563b6705706005e257aa65
Author: Vignesh Shanmugam <vignesh.shanmugam22@gmail.com>
Date:   2019-03-04T13:32:12+01:00 (2 years, 1 month ago)

    fix: rum agent to be symlinked before npm install

diff --git a/.gitignore b/.gitignore
index 6c96c5c..a9e1262 100644
--- a/.gitignore
+++ b/.gitignore
@@ -13,3 +13,10 @@ build
 .DS_Store
 .env
 npm-debug.log
+
+# master branch of rum agent
+elastic-apm-rum
+
+#lockfiles
+yarn.lock
+package-lock.json
```

there was intent (at least for the "client/" sub-directory) to not use lock files.

**Review by cachedout — APPROVED** [review]

**Comment by kuisathaverat** [comment]
@trentm Is there a way to use fixed versions for all packages but the client?

**Comment by trentm** [comment]
@kuisathaverat 

Please ignore my comment about the "client/" subdirectory. That dir comes from cloning a separate repo.

> Is there a way to use fixed versions for all packages but the client?

Yes, adding a package-lock.json as you have done here will do that.
However, I have a question. If I do an `npm install` in opbeans-node.git currently, I get:

```
% npm install
...
npm notice created a lockfile as package-lock.json. You should commit this file.
added 432 packages from 261 contributors and audited 433 packages in 180.674s

35 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

In other words: there are no current security issues.

I don't object to adding a package-lock.json file to opbeans-node.git, but what is the main reason for doing so? If we *do* add a package-lock.json then we will not get security patch releases from dependencies automatically as they are released. Instead we'll have to have some process to look out for those and explicitly commit and update to the package-lock.json file. Do we have a process for that? Or is it just "take a look occasionally"?

**Comment by mdelapenya** [comment]
I think they automated will be provided by #73

**Comment by trentm** [comment]
> I think the automated process to look out for new dependencies will be provided by #73

Okay, thanks.

**Review by trentm — APPROVED** [review]

**Comment by kuisathaverat** [comment]
> @kuisathaverat
> 
> Please ignore my comment about the "client/" subdirectory. That dir comes from cloning a separate repo.
> 
> > Is there a way to use fixed versions for all packages but the client?
> 
> Yes, adding a package-lock.json as you have done here will do that.
> However, I have a question. If I do an `npm install` in opbeans-node.git currently, I get:
> 
> ```
> % npm install
> ...
> npm notice created a lockfile as package-lock.json. You should commit this file.
> added 432 packages from 261 contributors and audited 433 packages in 180.674s
> 
> 35 packages are looking for funding
>   run `npm fund` for details
> 
> found 0 vulnerabilities
> ```
> 
> In other words: there are no current security issues.
> 
> I don't object to adding a package-lock.json file to opbeans-node.git, but what is the main reason for doing so? If we _do_ add a package-lock.json then we will not get security patch releases from dependencies automatically as they are released. Instead we'll have to have some process to look out for those and explicitly commit and update to the package-lock.json file. Do we have a process for that? Or is it just "take a look occasionally"?

yep, I've made a fresh checkout and the audit does not report issues, so I made something wrong in the first place. The main reason for add the `package-lock.json` is for repeatability, I mean, without this file you can not ensure you will generate the same binary if you build the Docker image, this is bad because you will not be able to replicate an issue on the image or you will introduce a new error or security issue without being aware of it. Dependency updates should be managed to avoid ugly situations.

**Pull request merged**
