### PR TITLE
Bump node agent version 3.0.0

### PR DESCRIPTION
**Pull request by v1v**
See [3.0.0](https://github.com/elastic/apm-agent-nodejs/releases/tag/v3.0.0)

### CODE REVIEW

**Comment by watson** [comment]
We should probably upgrade to v3.0.0. The breaking changes are not that complicated and an upgrade guide can be found here: https://www.elastic.co/guide/en/apm/agent/nodejs/current/upgrade-to-v3.html

**Comment by watson** [comment]
@v1v

> I went through the https://www.elastic.co/guide/en/apm/agent/nodejs/current/upgrade-to-v3.html and I could not find any references to the deprecated methods. I guess those changes were done with 188e956

Do you mean you couldn't find the methods in the docs? I didn't link to them because they are no longer in the `current` docs. But if you go to the `2.x` docs they are there. But their API's are 100% identical, so it should just be changing the name of the function call and you should be ok.

**Comment by v1v** [comment]
@watson , sorry about the misleading, I meant I've seen the migration from 2.x to 3.x was already done with https://github.com/elastic/opbeans-node/commit/188e956a6f7c9645c6464c366908ee66b1a1a571 

If so, I guess we are ready to merge this PR. Please let me know your thoughts

**Comment by watson** [comment]
Ah got ya. Yes, the "label" aliases existed back in 2.x as well, we just removed the deprecated old functions in 3.0.0 and in anticipation of this I updated the code a while back. So you're all good

**Pull request merged**
